### ISSUE TITLE
Headings not centered

### ISSUE THREAD

**Issue by ApolloZhu** [oaktoncsclub/oaktoncsclub.github.io#15]
I don't know how to fix this. Currently it looks like this:

``` html
<nav>
    <center class="blue nav-wrapper">
         <a href="#update" class="brand-logo" style="color:white;">Updates</a>
    </center>
</nav>
```
## FIXME
- https://github.com/oaktoncsclub/oaktoncsclub.github.io/blob/master/default.html#L38-L42
- https://github.com/oaktoncsclub/oaktoncsclub.github.io/blob/master/default.html#L80-L84
- https://github.com/oaktoncsclub/oaktoncsclub.github.io/blob/master/default.html#L144-L148
- https://github.com/oaktoncsclub/oaktoncsclub.github.io/blob/master/default.html#L184-L188

**Comment by dgramop** [comment]
Ill try using &lt center &gt, I think it is a problem with the library

**Comment by ApolloZhu** [comment]
Thanks

**Comment by dgramop** [comment]
Remember to use inline css only for quick jobs, otherwise you can "inherit" or use element{css} in the style tag

**Comment by dgramop** [comment]
I may also consider using position: relative and hardcoding some values (relative left a few percentages because relative to the pos it is supposed to be at, defined by the lib)

**Comment by ApolloZhu** [comment]
Make sure it is in the center for both desktop and mobile

**Comment by dgramop** [comment]
Fixed, see #16 . I always use percentages and rarely pixels for "hard coding". It should be fine on mobile

**Comment by dgramop** [comment]
You can pull when ready, I am moving to the next issue!

**Comment by ApolloZhu** [comment]
Thanks
