### ISSUE TITLE
ACSL Information page

### ISSUE THREAD

**Issue by ApolloZhu** [oaktoncsclub/oaktoncsclub.github.io#19]
I added [ACSL info page](https://github.com/oaktoncsclub/oaktoncsclub.github.io/blob/master/acsl.html). I'm currently very very busy, are there anyone available to make it look better?

**Comment by Oatkon-Computer-Science** [comment]
Pls add a link to the study materials: https://drive.google.com/drive/folders/0B6gu4YCPzMNdfkNJdzMtcmlac3JtUG4zcjJ2dU10eUE3OWgtdHJvZGgxOEQ2WV9xTllQb1E?usp=sharing
