### ISSUE TITLE
Add domains etc.

### ISSUE THREAD

**Issue by dgramop** [oaktoncsclub/oaktoncsclub.github.io#24]
Being the new webmaster for oakton CS club, I'd also like access to this repo as a collaborator and whatnot. 

https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/
https://help.github.com/articles/setting-up-an-apex-domain/

Please follow these tutorials for 
oakcsclub.win

A domain which I am donating 5 years worth to oakton

**Comment by ApolloZhu** [comment]
You and Andrew should now have admin permissions over this repository
