### ISSUE TITLE
Member List

### ISSUE THREAD

**Issue by ApolloZhu** [oaktoncsclub/oaktoncsclub.github.io#33]
Please add a list of members, and those who never paid club dues will be in ***red, bold in the front***.

**Comment by avonstar21** [comment]
Okay.

**Comment by ApolloZhu** [comment]
@avonstar21 Please organize all our spreadsheet, so we have a single one that looks like

|Name|Paid Dues|Meetings Attended|
|:--:|:--:|:--:|
|...|Y/N|#|

**Comment by FriendlyAI** [comment]
We will need to update this list periodically for members who later pay their dues.
