### ISSUE TITLE
"Meh" handling of members

### ISSUE THREAD

**Issue by dgramop** [oaktoncsclub/oaktoncsclub.github.io#34]
I can write a javascript that fetches the data from JSON and puts it onto the site so there's less HTML copy-pasting

**Comment by ApolloZhu** [comment]
We'll do this once the constitution is ratified by Mr. Lau, the school activity office, and then the Members.

**Comment by dgramop** [comment]
More importantly, the clause that releases their records & info to us

**Comment by ApolloZhu** [comment]
Can’t find old constitution, should/will address in the next meeting with the members page feature.
