### ISSUE TITLE
fjsdioadjfjsidf

### ISSUE THREAD

**Issue by asdffdsaasdffdsaasdffdsaasdf** [oaktoncsclub/oaktoncsclub.github.io#45]
is this how attendance works

**Comment by asdffdsaasdffdsaasdffdsaasdf** [comment]
i like tide pods

**Comment by TroyNeubauer** [comment]
==== web request ====
{
"name":"Apollo Zhu",
"email":"public-apollonian@outlook.com",
"template":{"name":"retro","type":"html"}
}
==== end web request ====
