### ISSUE TITLE
Daniel Hong

### ISSUE THREAD

**Issue by CatDanielH** [oaktoncsclub/oaktoncsclub.github.io#46]
==== web request ====
{
"name":"Daniel Hong",
"email":"skybluewingsdh@gmail.com",
"template":{"name":"retro","type":"html"}

}
==== end web request ====

**Comment by dgramop** [comment]
## Congrats!
Your site is now online at http://oakcsclub.win/members/CatDanielH/index.html

**Comment by dgramop** [comment]
You only used 3 equals, I added one for you
