### ISSUE TITLE
[Website request] Member webpage

### ISSUE THREAD

**Issue by FriendlyAI** [oaktoncsclub/oaktoncsclub.github.io#47]
==== web request ====
{
"name" : "Andrew Li",
"email" : "li.andrew.hua@gmail.com",
"template":{"name":"blank","type":"html"}
}
==== end web request ====

**Comment by dgramop** [comment]
You forgot the start and end request tags, added it for you

**Comment by dgramop** [comment]
## Congrats!
Your site is now online at http://oakcsclub.win/members/FriendlyAI/index.html
