### ISSUE TITLE
request to create site

### ISSUE THREAD

**Issue by ghost** [oaktoncsclub/oaktoncsclub.github.io#48]
Hi! I'm <Jonathan> <Guo>
==== web request ====
{
"name":"<Jonathan> <Guo>",
"template":{"type":"md","name":"retro"},
"email":"<jxguo@comcast.net>"
}
==== end web request ====

**Comment by dgramop** [comment]
## Congrats!
Your site is now online at http://oakcsclub.win/members/Jonathan-Guo/index.html
