### ISSUE TITLE
Please delete the other Jonathan Guo page and replace it with this one

### ISSUE THREAD

**Issue by asdffdsaasdffdsaasdffdsaasdf** [oaktoncsclub/oaktoncsclub.github.io#50]
I made a new account because I didn't want people to know the username I use for other stuff, but then it turns out I can just change my username which I didn't know.

**Comment by dgramop** [comment]
Will do

**Comment by dgramop** [comment]
Go ahead and re-submit a web request with the new account @JxGrasp
