### ISSUE TITLE
Jonathan Guo page request

### ISSUE THREAD

**Issue by asdffdsaasdffdsaasdffdsaasdf** [oaktoncsclub/oaktoncsclub.github.io#51]
Hi! I'm \<Jonathan> \<Guo>
==== web request ====
{
"name":"Jonathan Guo",
"template":{"type":"md","name":"retro"},
"email":"<jxguo@comcast.net>"
}
==== end web request ====

**Comment by dgramop** [comment]
## Congrats!
Your site is now online at http://oakcsclub.win/members/JxGrasp/index.html
