### ISSUE TITLE
Zhiqin web request

### ISSUE THREAD

**Issue by Zhiqin-He** [oaktoncsclub/oaktoncsclub.github.io#55]
hi, i'm Zhiqin He
==== web request ====
{
"name":"Zhiqin He",
"template":{"name":"retro","type":"html"},
"email":"zhiqinoct30@gmail.com"
}
==== end web request ====

**Comment by dgramop** [comment]
## Congrats!
Your site is now online at http://oakcsclub.win/members/Badly-Timed-Joke/index.html
